<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <Authors>Yuriy Lyeshchenko</Authors>
    <Description>Extension methods to simplify writing unit tests for code written using LanguageExt library</Description>
    <PackageProjectUrl>https://github.com/yuriylsh/LanguageExt.UnitTesting</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/yuriylsh/LanguageExt.UnitTesting</RepositoryUrl>
    <RepositoryUrl>https://github.com/yuriylsh/LanguageExt.UnitTesting.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>LanguageExt</PackageTags>
    <Copyright>Yuriy Lyeshchenko © 2018</Copyright>
    <MinVerTagPrefix></MinVerTagPrefix>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LanguageExt.Core" Version="4.4.9" />
    <PackageReference Include="MinVer" Version="7.0.0" PrivateAssets="all" />
  </ItemGroup>

</Project>
